name: Build and Deploy
on:
  push:
    paths: ["stories/**"]

jobs:
  build:
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Cache Node
        uses: actions/cache@v3
        id: cache-packages
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: cache-node-modules-

      - name: Install Node
        if: steps.cache-packages.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
      
      - name: Install
        run: yarn

      - name: Build
        run: yarn build-storybook

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'storybook-static'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
